version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/app
hooks:
  BeforeInstall:
    - location:
      timeout:
      runas:
  AfterInstall:
    - location:
      timeout:
      runas:
  ApplicationStart:
    - location:
    - location:
      timeout:
      runas:
  ApplicationStop:
    - location:
      timeout:
      runas:
